### ISSUE TITLE
Change locale of date time  picker

### ISSUE THREAD

**Issue by nmrusso** [aximsoftDevTeam/date-time-picker-solid#5]
How can you change the language of the date picker?

**Comment by aximsiva** [comment]
Are you asking about localization language changes?
Or 
Can you describe more on this

**Comment by nmrusso** [comment]
Exactly! I asking about a locale/language configuration.

**Comment by nmrusso** [comment]
From what I could see the package I understand that these are using a manual configuration. Could be? And neither i18n nor the moment configuration is being used.

**Comment by aximsiva** [comment]
We plan to add localization support in further releases.
